language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get build-dep libglib2.0-dev
script: ./autogen.sh && ./configure --enable-tests && make -j24 && make -j24 check && sudo make install
